services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  minio:
    image: 'minio/minio'
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
    volumes:
      - files:/data
  elastic:
    image: 'elasticsearch:7.14.0'
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;      
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
  account:
    image: anticrm/account
    links:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://localhost:3333
  front:
    image: anticrm/front
    links:
      - mongodb
      - minio
      - elastic
      - transactor
    ports:
      - 8081:8080
    environment:
      - ACCOUNTS_URL=http://localhost:3000
      - UPLOAD_URL=/files
      - TRANSACTOR_URL=ws://localhost:3333
      - ELASTIC_URL=http://elastic:9200
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin  
  transactor:
    image: anticrm/transactor
    links:
      - mongodb
      - elastic
    ports:
      - 3333:3333
    environment:
      - ELASTIC_URL=http://elastic:9200
      - MONGO_URL=mongodb://mongodb:27017
volumes:
  db:
  files:
  elastic:
