apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: app
          image: hardcoreeng/account
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: url
            - name: TRANSACTOR_URL
              value: wss://transactor.hc.engineering/
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: endpoint
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secretKey
