version: "3"
services:
  mongodb:
    image: 'mongo:7-jammy'
    command: mongod --port 27018
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27018:27018
    restart: unless-stopped
  minio:
    image: 'minio/minio'
    command: server /data --address ":9000"
    expose:
      - 9000
    ports:
      - 9002:9000
  elastic:
    image: 'elasticsearch:7.14.2'
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;      
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    expose:
      - 9200
    ports:
      - 9201:9200
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
  account:
    image: hardcoreeng/uberflow-account
    links:
      - mongodb
      - minio
    ports:
      - 3003:3003
    volumes:
      - ./branding-test.json:/var/cfg/branding-test.json
    environment:
      - ACCOUNT_PORT=3003
      - SERVER_PORT=3003
      - SERVER_SECRET=secret
      - MONGO_URL=mongodb://mongodb:27018
      - TRANSACTOR_URL=ws://transactor:3334
      - ENDPOINT_URL=ws://localhost:3334
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - FRONT_URL=http://front:8083
      - BRANDING_PATH=/var/cfg/branding-test.json
  collaborator:
    image: hardcoreeng/uberflow-collaborator
    links:
      - mongodb
      - minio
      - transactor
    ports:
      - 3079:3079
    environment:
      - COLLABORATOR_PORT=3079
      - SECRET=secret
      - ACCOUNTS_URL=http://account:3003
      - TRANSACTOR_URL=ws://transactor:3334
      - UPLOAD_URL=/files
      - MONGO_URL=mongodb://mongodb:27018
      - STORAGE_CONFIG=${STORAGE_CONFIG}
  front:
    image: hardcoreeng/uberflow-front
    links:
      - mongodb
      - minio
      - elastic
      - transactor
    ports:
      - 8083:8083
    volumes:
      - ./branding-test.json:/app/dist/branding-test.json
    environment:
      - SERVER_PORT=8083
      - SERVER_SECRET=secret
      - MONGO_URL=mongodb://mongodb:27018
      - ACCOUNTS_URL=http://localhost:3003
      - REKONI_URL=http://localhost:4007
      - COLLABORATOR_URL=ws://localhost:3079
      - COLLABORATOR_API_URL=http://localhost:3079
      - CALENDAR_URL=http://localhost:8095
      - GMAIL_URL=http://localhost:8088
      - TELEGRAM_URL=http://localhost:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - BRANDING_URL=http://localhost:8083/branding-test.json
  transactor:
    image: hardcoreeng/uberflow-transactor
    links:
      - mongodb
      - elastic
      - minio
      - rekoni
    ports:
      - 3334:3334
    volumes:
      - ./branding-test.json:/var/cfg/branding-test.json
    environment:
      - SERVER_PORT=3334
      - SERVER_SECRET=secret
      - ELASTIC_URL=http://elastic:9200
      - MONGO_URL=mongodb://mongodb:27018
      - FRONT_URL=http://localhost:8083
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - REKONI_URL=http://rekoni:4007
      - INTERCOM_SECRET_KEY=
      - ACCOUNTS_URL=http://account:3003
      - LAST_NAME_FIRST=true
      - ELASTIC_INDEX_NAME=local_storage_index
      - UPLOAD_URL=http://localhost:8083/files
      - BRANDING_PATH=/var/cfg/branding-test.json
  qms-workers:
    image: hardcoreeng/qms-workers
    restart: always
    links:
      - transactor
      - account
    environment:
      - SECRET=secret
      - TRANSACTOR_URL=ws://transactor:3334
      - ACCOUNTS_URL=http://account:3003
  rekoni:
    image: hardcoreeng/rekoni-service
    restart: on-failure
    ports:
      - 4007:4004
    deploy:
      resources:
        limits:
          memory: 1024M
volumes:
  files:
